version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/app
    networks:
      - backend

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/app
    networks:
      - backend
    ports:
      - "80:80"
  
  postgres:
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/persist:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
     - backend
    ports:
      - "54320:5432"


networks:
  backend: